CREATE TABLE GENDER (
    ID INT NOT NULL, 
    NAME VARCHAR(20)
);

ALTER TABLE GENDER ADD CONSTRAINT PK_GENDER PRIMARY KEY (ID);



CREATE TABLE OCCUPATION (
    ID INT NOT NULL,
    NAME VARCHAR(30)
);

ALTER TABLE OCCUPATION ADD CONSTRAINT PK_OCCUPATION PRIMARY KEY (ID);



CREATE TABLE USERS (
    ID INT NOT NULL,
    USERNAME VARCHAR(30),
    EMAIL VARCHAR(30),
    PASSWORD VARCHAR(20),
    GENDER_ID INT,
    OCCUPATION_ID INT
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_1 FOREIGN KEY (GENDER_ID) REFERENCES GENDER (ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_2 FOREIGN KEY (OCCUPATION_ID) REFERENCES OCCUPATION (ID);
ALTER TABLE USERS ADD CONSTRAINT CK_EMAIL_USERS CHECK EMAIL LIKE '%@%.%';
ALTER TABLE USERS ADD CONSTRAINT CK_PASSWORD_USERS CHECK LENGTH(PASSWORD)>5;



CREATE TABLE COOKIES (
    ID INT NOT NULL,
    COOKIE VARCHAR(30),
    TASTY BOOL DEFAULT TRUE,
    EXPIRED DATE NOT NULL
);

ALTER TABLE COOKIES ADD CONSTRAINT PK_COOKIES PRIMARY KEY (ID);



CREATE TABLE METADATA (
    USERS_ID INT,
    COOKIES_ID INT,
    TIME_ADDED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ENABLED BOOL DEFAULT TRUE 
);

ALTER TABLE METADATA ADD CONSTRAINT FK_METADATA_1 FOREIGN KEY (USERS_ID) REFERENCES USERS (ID);
ALTER TABLE METADATA ADD CONSTRAINT FK_METADATA_2 FOREIGN KEY (COOKIES_ID) REFERENCES COOKIES (ID);
CREATE INDEX METADATA_IDX1 ON METADATA (TIME_ADDED); 