SELECT *
FROM MetaData;

SELECT *
FROM User
ORDER BY ID;

SELECT *
FROM Cookies
ORDER BY ID;

SELECT DISTINCT DOB
FROM USER
ORDER BY DOB;

SELECT
  USERNAME,
  EMAIL
FROM USER
WHERE DOB = 1980;

SELECT
  'Customer',
  LOWER(USERNAME) AS Surname,
  EMAIL
FROM USER
WHERE DOB NOT IN (1975, 1985);

SELECT TITLE
FROM COOKIES
WHERE COOKED = TRUE AND exists(SELECT COOKIESID
                               FROM METADATA
                               WHERE COOKIESID = ID);

SELECT
  u.USERNAME  AS Surname,
  u.FIRSTNAME AS Name,
  m.COOKIESID AS Biscuit
FROM USER u, METADATA m
WHERE u.ID = m.USERID;

SELECT
  u.FIRSTNAME  AS Name,
  u.USERNAME   AS Surname,
  c.MESSAGE,
  m.TIME_ADDED AS TIME
FROM USER u, METADATA m, COOKIES c
WHERE u.ID = m.USERID AND c.ID = m.COOKIESID;

SELECT
  u.USERNAME,
  u.FIRSTNAME,
  c.TITLE
FROM COOKIES c, USER u
  INNER JOIN METADATA m ON m.COOKIESID = c.ID AND m.USERID = u.ID
ORDER BY u.FIRSTNAME;



