//Create tables in database
CREATE TABLE IF NOT EXISTS users
	(
		id INT PRIMARY KEY,
		username VARCHAR(30) NOT NULL UNIQUE,
		email VARCHAR(50) NOT NULL UNIQUE,
		password VARCHAR(40) NOT NULL
	);

ALTER TABLE users ADD CONSTRAINT EMAIL_CHECK CHECK (email LIKE '%@%.%');

CREATE TABLE IF NOT EXISTS cookies
	(
		id INT PRIMARY KEY AUTO_INCREMENT,
		cookie VARCHAR(100) NOT NULL
	);

CREATE TABLE IF NOT EXISTS metadata
	(
		id INT PRIMARY KEY AUTO_INCREMENT,
		cookie_id INT NOT NULL,
		user_id INT NOT NULL,
		time_added TIMESTAMP NOT NULL,
		FOREIGN KEY(cookie_id) REFERENCES cookies(id) ON UPDATE CASCADE,
		FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE
	);