ALTER TABLE USERS 
ADD COLUMN yearOfBirth year(4);

UPDATE USERS SET YEAROFBIRTH=1988 WHERE ID=1;
UPDATE USERS SET YEAROFBIRTH=1990 WHERE ID=2;
UPDATE USERS SET YEAROFBIRTH=1999 WHERE ID=3;
UPDATE USERS SET YEAROFBIRTH=2000 WHERE ID=4;
UPDATE USERS SET YEAROFBIRTH=1987 WHERE ID=5;
UPDATE USERS SET YEAROFBIRTH=1970 WHERE ID=6;
UPDATE USERS SET YEAROFBIRTH=1983 WHERE ID=7;
UPDATE USERS SET YEAROFBIRTH=1988 WHERE ID=8;

SELECT * from USERS 
ORDER BY ID;


 