SELECT* FROM USERS;
SELECT* FROM COOKIES;
SELECT* FROM METADATA;

SELECT U.USERNAME, C.COOKIE, M.TIME_ADDED
  FROM USERS U JOIN COOKIES C JOIN METADATA M
  ON U.ID = M.USER_ID  AND C.ID = M.COOKIE_ID;

SELECT U.USERNAME, U.EMAIL, C.COOKIE, C.PREDICTION
  FROM USERS U JOIN COOKIES C JOIN METADATA M ON
  U.ID = M.USER_ID AND C.ID = M.COOKIE_ID AND U.EMAIL LIKE '___@gm.com';