DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
	(
		ID INT PRIMARY KEY AUTO_INCREMENT,
		USERNAME VARCHAR(30) NOT NULL UNIQUE,
		EMAIL VARCHAR(50) NOT NULL UNIQUE,
		PASSWORD VARCHAR(40) NOT NULL,
		FIRST_NAME VARCHAR(30) NOT NULL,
		LAST_NAME VARCHAR(30) NOT NULL,
		AGE INT NOT NULL
	);
ALTER TABLE USERS ADD CONSTRAINT EMAIL_CHECK CHECK (EMAIL LIKE '%@%.%');
ALTER TABLE USERS ADD CONSTRAINT AGE_CHECK CHECK (AGE BETWEEN 1 AND 99);
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, AGE)
VALUES('Admin', 'admin@mail.com', 'password', 'Admin', 'Admin', 1);

DROP TABLE IF EXISTS COOKIES;
CREATE TABLE COOKIES
	(
		ID INT PRIMARY KEY AUTO_INCREMENT,
		COOKIE VARCHAR(100) NOT NULL,
		LUCKY_NUMBER INT NOT NULL
	);
ALTER TABLE COOKIES ADD CONSTRAINT COOKIE_UNIQUE UNIQUE(COOKIE);
ALTER TABLE COOKIES ADD CONSTRAINT LUCKY_UNIQUE UNIQUE(LUCKY_NUMBER);
ALTER TABLE COOKIES ADD CONSTRAINT LUCKY_NOT_NEGATIVE CHECK (LUCKY_NUMBER > 0);

INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('Life is too short to hold grudges', 13);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('Make a wish, it might come true', 7);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('Look to your inner being for guidance', 666);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('A frivolous gift is a gift, nonetheless', 777);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('You will have long and healthy life', 21);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('You learn about another person in the process of teaching them something', 999);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('Dream your dream and your dream will dream of you', 12);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('Relish the transitions in your life - they will happen anyway', 25);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('The time is right to make new friends', 69);
INSERT INTO COOKIES (COOKIE, LUCKY_NUMBER) VALUES('You are filled with a sense of urgency. Be patient or you may end up confused', 100);

DROP TABLE IF EXISTS METADATA;
CREATE TABLE METADATA
	(
		ID INT PRIMARY KEY AUTO_INCREMENT,
		COOKIE_ID INT NOT NULL,
		USER_ID INT NOT NULL,
		TIME_ADDED TIMESTAMP NOT NULL,
		FOREIGN KEY(COOKIE_ID) REFERENCES COOKIES(ID) ON UPDATE CASCADE,
		FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON UPDATE CASCADE
	);