package com.epam.first;

public enum ParseTagNames {
    PLAY, TITLE, FM, P, PERSONAE, PGROUP, PERSONA, GRPDESCR, SCNDESCR, PLAYSUBT, INDUCT, ACT, SCENE, PROLOGUE,
    EPILOGUE, SPEECH, SPEAKER, LINE, STAGEDIR, SUBTITLE, SUBHEAD
}
