CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR NOT NULL UNIQUE CHECK (LENGTH(USERNAME) >= 2),
    EMAIL VARCHAR NOT NULL UNIQUE CHECK (EMAIL LIKE '%@%.%'),
    PASSWORD VARCHAR NOT NULL CHECK (LENGTH(PASSWORD) >= 6)
);

CREATE TABLE COOKIES(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    COOKIE VARCHAR NOT NULL CHECK (LENGTH(COOKIE) > 3),
    PREDICTION VARCHAR NOT NULL
);

CREATE TABLE METADATA(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    COOKIE_ID INTEGER,
    USER_ID INTEGER,
    TIME_ADDED TIMESTAMP,
    FOREIGN KEY(COOKIE_ID) REFERENCES COOKIES(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);