package elements;

public enum TagNames {
    PLAY, TITLE, FM, P, PERSONAE, PGROUP, PERSONA, GRPDESCR, SCNDESCR, PLAYSUBT, INDUCT, ACT,
    SCENE, PROLOGUE, EPILOGUE, SPEECH, SPEAKER, LINE, STAGEDIR, SUBTITLE, SUBHEAD
}
